export const QUERY_CONSTANT = {
    GET_LOGGED_IN_USER: 'GET_LOGGED_IN_USER',
    GET_UPLOAD_URL: 'GET_UPLOAD_URL',
    USER_PROFILE_IMAGE: 'USER_PROFILE_IMAGE',
    DELETE_FILE: 'DELETE_FILE',
    GET_TIMEZONES: 'GET_TIMEZONES',
    GET_COUNTRIES: 'GET_COUNTRIES',
    GET_LANGUAGES: 'GET_LANGUAGES',
};
